// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drsegsrfnshzhnpgvgib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyc2Vnc3JmbnNoemhucGd2Z2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODQyNTMsImV4cCI6MjA2ODM2MDI1M30.0jT8ZhGiohUO1_NvAi-8EqpYZGwGDnqOA-7Ifq8FD6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});